apiVersion: v1
kind: Secret
metadata:
  name: gitlab-scampml-ede-puller
type: kubernetes.io/dockerconfigjson
# change dockerconfigjson !!!
data:
  .dockerconfigjson: $base64({"auths":{"registry.dev.scamp.roiot.ro":{"username":"username","password":"password","auth":"$base64(username:password)"}}})
