apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scampml-ede-etc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-client"